include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - use_key_in_widget_constructors
    - avoid_unused_constructor_parameters
    - sort_child_properties_last

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"